README.md
This is just a test merge to see if my instructions are correct.
=> Updating readme to test pull requests on GitHub

README.md
Reverts FluffySheep/CodeU2019-Team28#1
Accidentally merged to master
=> Revert "Updating readme to test pull requests on GitHub"

src/main/webapp/WEB-INF/appengine-web.xml
Updates our App ID provided by the CodeU team so that we can push to the live website at https://sp19-codeu-28-4865.appspot.com/
=> Updates the App ID provided by CodeU team.

src/main/webapp/index.html
Updated the main page text to say "Brian is the awesomest PA ;)."
=> Updated the main page text.

src/main/java/com/google/codeu/servlets/MessageServlet.java
Modified code to fix compile error from adding recipient to Message.java. Also changed the curly brackets.
=> Modified code to allow recipient

src/main/java/com/google/codeu/data/Datastore.java
Fixed the last modification regarding recipients that caused compile errors. Curly brackets again :)
=> last commit for the week

src/main/java/com/google/codeu/data/Datastore.java, src/main/java/com/google/codeu/data/Message.java, src/main/java/com/google/codeu/servlets/MessageServlet.java
Added a recipient variable to Message.java and changed the position of the curly brackets because I like seeing the blocks of code properly.
=> Adds the concept of recipients to Messaages, MessageServlets, and DataStore

src/main/java/com/google/codeu/data/Message.java
Java formatter usage.
1. On windows, right click and open git bash in your CodeU2019-Team28 directory (this should be the top level directory of our project). On Mac / Linux, cd into CodeU2019-Team28.
2. Type `java -jar formatter.jar --replace $(git ls-files|grep \.java$)`
This will go through all the java files and fix the formatting of them.
=> Adds a Java formatter to the project.

src/main/java/com/google/codeu/servlets/AboutMeServlet.java, src/main/java/com/google/codeu/servlets/LoginServlet.java, src/main/java/com/google/codeu/servlets/LoginStatusServlet.java, src/main/java/com/google/codeu/servlets/LogoutServlet.java
Completed Step 2 for Familiarization Project: About Me.
=> Completed Step 2 for Familiarization Project: About Me.

src/main/webapp/js/user-page-loader.js, src/main/webapp/user-page.html
=> Added html and js to display an 'about me' description on the user page along withthe ability to edit the description

README.md, src/main/java/com/google/codeu/data/Datastore.java, src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
Created Message Feed Servlet for public feed feature
=> Created Message Feed Servlet

src/main/webapp/js/user-page-loader.js
modified function to let user see form as long as they're logged in
=> Changed showMessageFormIfViewingSelf() function so user can see the message form as long as they're logged in even if it isn't viewing self

src/main/java/com/google/codeu/data/Datastore.java
I modified getmessages() function to return messages back to a user as the recipient
=> Change getMessages function recipient variable to user.

src/main/java/com/google/codeu/servlets/MessageFeedServlet.java, src/main/webapp/feed.html
=> Implemented UI for Message Feed with HTML

README.md, src/main/java/com/google/codeu/data/Datastore.java, src/main/java/com/google/codeu/data/Message.java, src/main/java/com/google/codeu/data/User.java, src/main/java/com/google/codeu/servlets/AboutMeServlet.java, src/main/java/com/google/codeu/servlets/LoginServlet.java, src/main/java/com/google/codeu/servlets/LoginStatusServlet.java, src/main/java/com/google/codeu/servlets/LogoutServlet.java, src/main/java/com/google/codeu/servlets/MessageFeedServlet.java, src/main/java/com/google/codeu/servlets/MessageServlet.java, src/main/java/com/google/codeu/servlets/StatsPageServlet.java, src/main/webapp/feed.html, src/main/webapp/index.html, src/main/webapp/js/user-page-loader.js, src/main/webapp/stats.html, src/main/webapp/user-page.html
Familiarization Projects Release
- [Public Feed ](https://sites.google.com/corp/codeustudents.com/spring-2019/weeks-1-2-familiarization-projects/public-feed?authuser=2)
- [Stats Page](https://sites.google.com/corp/codeustudents.com/spring-2019/weeks-1-2-familiarization-projects/stats-page?authuser=2)
- [Direct Messages](https://sites.google.com/corp/codeustudents.com/spring-2019/weeks-1-2-familiarization-projects/direct-messages?authuser=2)
- [About Me](https://sites.google.com/corp/codeustudents.com/spring-2019/weeks-1-2-familiarization-projects/about-me?authuser=2)
=> Release 1.1.0 3/4/2019

.stickler.yml, README.md, src/main/webapp/WEB-INF/appengine-web.xml, src/main/webapp/index.html
Features:
- Stickler CI linter for java.
- App ID to GCP ID (sp19-codeu-28-4865)
- Main Page Description change
=> Initial Repository Setup

src/main/webapp/js/user-page-loader.js, src/main/webapp/user-page.html
=> [kpcasta] From PR #27: Added html and js to display an 'about me' description on the user page along withthe ability to edit the description

src/main/webapp/Maps/maps1.html
I made a new HTML and followed the steps to set up a new maps project using google maps API. When I ran it on localhost it showed a map of the Google Mountain View office and has zoom in/out functions. It also has a function that allows the user to see a 360-degree view of a particular location.
=> setup skeleton of maps project

src/main/webapp/Maps/maps1.html
I added an information tag for red markers on the map so when the user hovers over the marker, they can see the name of the place marked and when they click, they can get a little more information about the place
=> Information Window for Red Markers

pom.xml, src/main/java/com/google/codeu/data/Datastore.java, src/main/java/com/google/codeu/data/Message.java, src/main/java/com/google/codeu/servlets/AboutMeServlet.java, src/main/java/com/google/codeu/servlets/MessageServlet.java, src/main/webapp/js/user-page-loader.js
This addition included updating Message and Datastore classes to store the sentimentScore variable along with updating the user-page-loader.js to reflect the sentimentScore on message postings.
=> Created a new helper function in the MessageServlet that uses Google Natural Language API to return the sentiment score for a given user input text. 

src/main/webapp/Maps/user-map.html
Added a new HTML file with hardcoded longitude and latitude values to display a marker on a map using the addListener() function. 
An example of what it looks like:
=> added a new user map

src/main/webapp/Maps/user-map.html
User can now open only one marker at a time. Any information they add is also stored.
=> PR #67: Modified info windows behaviour for maps.

README.md, src/main/java/com/google/codeu/data/Datastore.java, src/main/webapp/index.html
I performed a `git rebase -i 7707cd18ffb1a06c3218aa71810979179fed690f` on the develop branch and used a wide sweeping blind `git checkout --theirs . && git add . && git rebase --continue`.
The command mostly went smooth but some history was overwritten. Below are the changes that differ between the old develop and the rebased develop.
=> PR N/A: Added deleted code when performing git rebase history cleanup.

.eslintrc, .gitignore, .stickler.yml, checkstyle.xml, src/main/webapp/WEB-INF/appengine-web.xml, src/main/webapp/index.html
Features:
- Initial Project Setup
=> PR #72: Feb 10, 2019: Release Cut

.eslintrc, .gitignore, .stickler.yml, checkstyle.xml, src/main/webapp/WEB-INF/appengine-web.xml, src/main/webapp/index.html
Features:
- Initial Project Setup
=> PR #74: Feb 10, 2019: Release Cut

README.md, src/main/java/com/google/codeu/data/Datastore.java, src/main/java/com/google/codeu/data/Message.java, src/main/java/com/google/codeu/servlets/AboutMeServlet.java, src/main/java/com/google/codeu/servlets/LoginServlet.java, src/main/java/com/google/codeu/servlets/LoginStatusServlet.java, src/main/java/com/google/codeu/servlets/LogoutServlet.java, src/main/java/com/google/codeu/servlets/MessageFeedServlet.java, src/main/java/com/google/codeu/servlets/MessageServlet.java, src/main/webapp/js/user-page-loader.js, src/main/webapp/user-page.html
=> PR #75: Feb 24, 2019: Release Cut

src/main/java/com/google/codeu/servlets/MessageServlet.java, src/main/webapp/css/user-page.css
Translates text/Image URL to image
=> PR: #63: Images Part 1

src/main/java/com/google/codeu/servlets/MessageServlet.java, src/main/webapp/css/user-page.css
Reverts FluffySheep/CodeU2019-Team28#63
Build is broken.
=> Revert "PR: #63: Images Part 1"

src/main/java/com/google/codeu/servlets/MessageServlet.java, src/main/webapp/css/user-page.css
Added userText string var to messageServlet
Fixed merge conflicts
=> PR #101: Add userText string var that was breaking the build.

src/main/webapp/user-page.html
=> PR #99: Add "Upload New Profile Picture" heading, related to PR #96

src/main/java/com/google/codeu/servlets/ImageUploadUrlServlet.java, src/main/java/com/google/codeu/servlets/MessageServlet.java, src/main/webapp/css/user-page.css, src/main/webapp/user-page.html
Allows the user access and select an image to upload
=> PR: #96: Images Part 2

src/main/java/com/google/codeu/data/UserMarker.java, src/main/webapp/Maps/geocode-map.html
I made changes to the geocodemap,html file so when a user types in a location, the location appears as a marker on their map and the formatted address appears when the marker is clicked (for this example I typed in "2251 Sherman Ave NW Washington").
=> PR #105: User location marker

src/main/webapp/Maps/geocode-map.html, src/main/webapp/user-page.html
Map displays on the user page and I added a location box for the user information so when the submit button is clicked it sends the address to the function and displays it on the map. Submit button does not work yet.
=> PR #110: Added map to user the page

src/main/webapp/index.html
=> PR #111 : Adds the maps feature to the home page navigation.

src/main/webapp/feed.html
=> PR #106 : Fixes feed page UI from not rendering.

src/main/webapp/user-page.html
If you click the submit button, in develop, an error is thrown in the console "An invalid form control with name=‘text’ is not focusable". The fix was to remove the required field.
=> PR #115: Fix all userpage submit buttons throw a focusable error.

src/main/java/com/google/codeu/data/User.java
Changed User class variables and added set/get methods
=> PR #122: Updated User Class

src/main/java/com/google/codeu/data/User.java, src/main/java/com/google/codeu/servlets/ImageUploadUrlServlet.java, src/main/java/com/google/codeu/servlets/ProfileImageServlet.java
*Created connection to Blobstore
=> Change Profile Picture

src/main/java/com/google/codeu/data/User.java, src/main/java/com/google/codeu/servlets/AboutMeServlet.java, src/main/webapp/js/user-page-loader.js, src/main/webapp/user-page.html
Moved map loading functions from user-page.html to user-page-loader.js. Also added functions that adds the about me info input by the user to a json object.
=> PR #124: First set of changes for submit button

src/main/java/com/google/codeu/data/Datastore.java, src/main/java/com/google/codeu/data/User.java, src/main/java/com/google/codeu/servlets/AboutMeServlet.java
=> Updating User in Datastore
